version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
